# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
#title:               Saylor Electro-Acoustics
tagline:             'Where Sound Comes First'
description:         'Where Sound Comes First'
url:                 http://lanyon.getpoole.com
baseurl:             
plugins: [jekyll-paginate]
paginate:            5

# About/contact
author:
  name:              Brad Saylor
  url:               https://twitter.com/mdo
  email:             bradsayloremail@gmail.com

# Custom vars
version:             1.0.0
